_id: 5e2f047b29ee181c161a73b9
archive: 5e2f047d29ee181c161a73ba
courseid: LINFO1002-P1
custom: {}
grade: 0.0
input:
    '@lang': en
    '@random': []
    '@state': ''
    '@username': mpiraux
    q1: ' '
problems: {}
response_type: rst
result: failed
state: ''
status: done
stderr: ''
stdout: |+
    ======================================================================
    FAIL: test_median (TestMedian.TestMedian)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "./src/TestMedian.py", line 21, in test_median
    AssertionError: 49 != 0 : The median of [87, 9, 49] is 49 and you returned 0.

    ======================================================================
    FAIL: test_specific_median (TestMedian.TestMedian)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "./src/TestMedian.py", line 30, in test_specific_median
    AssertionError: 85 != 0 : The median of [85, 86, 84] is 85 and you returned 0.

    ----------------------------------------------------------------------
    Ran 2 tests in 0.000s

    FAILED (failures=2)

submitted_on: 2020-01-27 16:40:43.807000
taskid: Median
tests: {}
text: |+
    It seems that you have made mistakes in your codeâ€¦



    .. code-block:: python

        Failed test:
        49 != 0 : The median of [87, 9, 49] is 49 and you returned 0.

        Failed test:
        85 != 0 : The median of [85, 86, 84] is 85 and you returned 0.

        ----------------------------------------------------------------------
        Ran 2 tests in 0.000s

        FAILED (failures=2)


username:
- mpiraux
